name: lintly-flake8

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  lintly-flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          failIf: new
          args: "."
          token: ${{ secrets.GITHUB_TOKEN }}
